networks:
  app-network:
    driver: bridge

services:
  # nginx
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - ${WEB_DIRECTORY}:/var/www/
      - ./services/nginx/sites-enabled:/etc/nginx/conf.d/
    depends_on:
      - php74-service
      - php80-service
      - php84-service
      - mysql8-service
      - real-estate-price
    networks:
      - app-network

  # php
  php74-service:
    build:
      context: ./services/php-fpm
      dockerfile: Dockerfile
      args:
        - PHP_VERSION=7.4-fpm
        - INSTALL_COMPOSER=true
    container_name: php74-container
    volumes:
      - ${WEB_DIRECTORY}:/var/www/
      - ./services/php-fpm/config/php7.4.ini:/usr/local/etc/php/php.ini
    networks:
      - app-network

  php80-service:
    build:
      context: ./services/php-fpm
      dockerfile: Dockerfile
      args:
        - PHP_VERSION=8.0-fpm-alpine
        - INSTALL_COMPOSER=true
    container_name: php80-container
    volumes:
      - ${WEB_DIRECTORY}:/var/www/
      - ./services/php-fpm/config/php8.0.ini:/usr/local/etc/php/php.ini
    networks:
      - app-network

  php84-service:
    build:
      context: ./services/php-fpm
      dockerfile: Dockerfile
      args:
        - PHP_VERSION=8.4-fpm-alpine
        - INSTALL_COMPOSER=true
    container_name: php84-container
    volumes:
      - ${WEB_DIRECTORY}:/var/www/
      - ./services/php-fpm/config/php8.4.ini:/usr/local/etc/php/php.ini
    networks:
      - app-network

  # mysql
  mysql8-service:
    build:
      context: ./services/mysql
      args:
        - MYSQL_VERSION=8.4.6
    container_name: mysql8-container
    ports:
      - "5501:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - app-network

  # Python - FastAPI
  real-estate-price:
    build:
      context: ../real-estate-price-predictor
    container_name: real-estate-price-container
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ../real-estate-price-predictor:/app
    expose:
      - "8000"
    networks:
      - app-network
  
  # Golang API Service
  golang-api:
    build:
      context: ../golang-api-service
      dockerfile: Dockerfile
    container_name: golang-api-container
    ports:
      - "9000:9000"
    volumes:
      - ../golang-api-service:/app
    depends_on:
      - mysql8-service
    networks:
      - app-network
